Repository Wabri/GestioneOrari, pull requests merged in 2020-06, with the labels that each got.

#14 Add (docs:README): more info put on README
  README.md
Labels: documentation

#16 15 - Update (Elaborato.java): can store Row instance in a List
  GestioneOrari/src/Elaborato/Elaborato.java
  GestioneOrari/src/Parser/Parser.java
  GestioneOrari/src/processed/ProcessedFile.java
  GestioneOrari/src/row/Row.java
Labels: enhancement

#28 Fix ( package ) : modified package name
  GestioneOrari/src/GestioneOrari.java
  GestioneOrari/src/parser/Parser.java
Labels: good first issue

#17 7 - Update (Parser.java): method parse completed
  GestioneOrari/src/GestioneOrari.java
  GestioneOrari/src/errors/WrongFormatException.java
  GestioneOrari/src/parser/Parser.java
Labels: enhancement

#33 32 - update gitignore
  .gitignore
Labels: good first issue

#35 9 - Update (Parser.java): Implemented method getDailyWorkHours
  src/GestioneOrari.java
  src/parser/Parser.java
Labels: enhancement

#36 34 - Fix (WrongFormatException.java): add serialVersionUID
  src/errors/WrongFormatException.java
Labels: enhancement, help wanted
